'use client'

import { useState } from 'react'
import { ArrowLeft, ArrowRight, Check, CheckCircle2, Eye, EyeOff, LockKeyhole, Mail, Phone, ShieldCheck, Stethoscope, UserRound, UsersRound } from 'lucide-react'

const roles = [
  { id: 'patient', title: 'Patient', copy: 'Book appointments and manage your care.', icon: UserRound },
  { id: 'doctor', title: 'Doctor', copy: 'Manage your practice and consultations.', icon: Stethoscope },
  { id: 'staff', title: 'Staff', copy: 'Support your clinic operations.', icon: UsersRound },
] as const

type Role = (typeof roles)[number]['id']
type Screen = 'login' | 'role' | 'signup' | 'forgot' | 'reset' | 'verify' | 'success'

function Field({ label, type = 'text', placeholder, icon: Icon, required = true }: { label: string; type?: string; placeholder?: string; icon?: typeof Mail; required?: boolean }) {
  const [visible, setVisible] = useState(false)
  const isPassword = type === 'password'
  return <label className="flex flex-col gap-2 text-sm font-semibold text-[#36515e]">
    <span>{label}{required && <span className="text-[#788f98]"> *</span>}</span>
    <span className="relative">
      {Icon && <Icon aria-hidden="true" className="absolute left-3.5 top-1/2 size-4 -translate-y-1/2 text-[#8da6ae]" />}
      <input type={isPassword && visible ? 'text' : type} placeholder={placeholder} className="h-11 w-full rounded-xl border border-[#d9e6e9] bg-white px-3.5 text-sm font-normal text-[#294652] outline-none transition placeholder:text-[#a7b8bd] focus:border-[#5367df] focus:ring-4 focus:ring-[#5367df]/10" />
      {isPassword && <button type="button" onClick={() => setVisible(!visible)} aria-label={visible ? 'Hide password' : 'Show password'} className="absolute right-3.5 top-1/2 -translate-y-1/2 text-[#8da6ae]">{visible ? <EyeOff className="size-4" /> : <Eye className="size-4" />}</button>}
    </span>
  </label>
}

function Brand() { return <div className="flex items-center gap-2.5"><span className="grid size-9 place-items-center rounded-xl bg-[#5367df] text-white shadow-lg shadow-[#5367df]/20"><Stethoscope className="size-5" /></span><span className="text-xl font-bold tracking-tight text-[#243f4c]">Medi<span className="text-[#5367df]">Book</span></span></div> }

function VisualPanel() { return <aside className="relative hidden overflow-hidden bg-[#253f91] lg:flex lg:w-[44%] lg:flex-col lg:justify-between lg:p-12">
  <div className="absolute -right-36 -top-32 size-[520px] rounded-full bg-[#6b7ff0]/30 blur-3xl" /><div className="absolute -bottom-32 -left-32 size-[440px] rounded-full bg-[#1a2b71]/70 blur-2xl" />
  <div className="relative"><Brand /><p className="mt-16 max-w-sm text-4xl font-semibold leading-[1.1] tracking-tight text-white">Care that feels <span className="text-[#9eafff]">personal.</span></p><p className="mt-5 max-w-sm text-base leading-7 text-[#d3dbff]">Your trusted space to find the right care, book appointments, and stay on top of your health.</p></div>
  <div className="relative mx-auto w-full max-w-sm"><div className="rounded-[2rem] border border-white/20 bg-white/10 p-5 backdrop-blur-xl"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-[#a8b6ff] text-[#253f91]"><UserRound className="size-5" /></div><div><p className="text-xs text-[#d3dbff]">Your next visit</p><p className="font-semibold text-white">Dr. Emily Carter</p></div></div><span className="rounded-full bg-[#c8f0d7] px-2.5 py-1 text-[10px] font-bold text-[#2d8054]">Confirmed</span></div><div className="mt-5 flex items-center gap-3 border-t border-white/15 pt-4 text-xs text-[#d3dbff]"><span className="rounded-lg bg-white/10 px-3 py-2 font-semibold text-white">Wed, 24 Apr</span><span>10:30 AM</span><span className="ml-auto">Video visit</span></div></div><div className="mt-4 flex items-center gap-2 text-xs text-[#d3dbff]"><ShieldCheck className="size-4 text-[#a8b6ff]" /> Your health data is private and secure</div></div>
</aside> }

function Login({ go }: { go: (screen: Screen) => void }) { const [loading, setLoading] = useState(false); return <AuthShell eyebrow="Welcome back" title="Sign in to your account" copy="Manage your appointments and stay connected to your care team."><form onSubmit={(e) => { e.preventDefault(); setLoading(true); setTimeout(() => setLoading(false), 900) }} className="flex flex-col gap-5"><Field label="Email address" type="email" placeholder="you@example.com" icon={Mail} /><Field label="Password" type="password" placeholder="Enter your password" icon={LockKeyhole} /><div className="flex items-center justify-between text-xs"><label className="flex items-center gap-2 font-medium text-[#607982]"><input type="checkbox" className="size-4 rounded border-[#c9dadd] accent-[#5367df]" /> Remember me</label><button type="button" onClick={() => go('forgot')} className="font-bold text-[#5367df]">Forgot password?</button></div><button disabled={loading} className="flex h-11 items-center justify-center gap-2 rounded-xl bg-[#5367df] text-sm font-bold text-white shadow-lg shadow-[#5367df]/20 transition hover:bg-[#4357cf] disabled:opacity-60">{loading ? 'Signing in...' : 'Sign in'} {!loading && <ArrowRight className="size-4" />}</button></form><Divider /><button className="flex h-11 items-center justify-center gap-3 rounded-xl border border-[#d9e6e9] bg-white text-sm font-bold text-[#36515e] hover:bg-[#f8fbfc]"><span className="text-base font-bold text-[#4285f4]">G</span> Continue with Google</button><p className="text-center text-sm text-[#6a8189]">New to MediBook? <button onClick={() => go('role')} className="font-bold text-[#5367df]">Create an account</button></p></AuthShell> }

function AuthShell({ eyebrow, title, copy, children }: { eyebrow: string; title: string; copy: string; children: React.ReactNode }) { return <div className="mx-auto w-full max-w-md"><div className="mb-10 lg:hidden"><Brand /></div><p className="text-sm font-bold text-[#5367df]">{eyebrow}</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-[#243f4c]">{title}</h1><p className="mt-3 text-sm leading-6 text-[#71878f]">{copy}</p><div className="mt-8">{children}</div></div> }
function Divider() { return <div className="my-6 flex items-center gap-3 text-xs font-medium text-[#a0b1b6]"><span className="h-px flex-1 bg-[#e1ebed]" />or<span className="h-px flex-1 bg-[#e1ebed]" /></div> }

function RoleChoice({ go, setRole }: { go: (screen: Screen) => void; setRole: (role: Role) => void }) { return <AuthShell eyebrow="Create your account" title="How will you use MediBook?" copy="Choose the option that best describes you. You can update your profile later."><div className="flex flex-col gap-3">{roles.map(({ id, title, copy, icon: Icon }) => <button key={id} onClick={() => { setRole(id); go('signup') }} className="group flex items-center gap-4 rounded-2xl border border-[#d9e6e9] bg-white p-4 text-left transition hover:border-[#5367df] hover:shadow-lg hover:shadow-[#5367df]/10"><span className="grid size-11 place-items-center rounded-xl bg-[#eef1ff] text-[#5367df] group-hover:bg-[#5367df] group-hover:text-white"><Icon className="size-5" /></span><span className="flex-1"><strong className="block text-sm text-[#294652]">{title}</strong><span className="mt-1 block text-xs text-[#82979f]">{copy}</span></span><ArrowRight className="size-4 text-[#afc0c5] group-hover:text-[#5367df]" /></button>)}</div><p className="mt-8 text-center text-sm text-[#6a8189]">Already have an account? <button onClick={() => go('login')} className="font-bold text-[#5367df]">Sign in</button></p></AuthShell> }

function Signup({ role, go }: { role: Role; go: (screen: Screen) => void }) { const roleTitle = role[0].toUpperCase() + role.slice(1); return <AuthShell eyebrow={`${roleTitle} account`} title="Create your account" copy="Set up your profile to get started with MediBook."><form onSubmit={(e) => { e.preventDefault(); go('verify') }} className="flex max-h-[55vh] flex-col gap-4 overflow-y-auto pr-1"><div className="grid gap-4 sm:grid-cols-2"><Field label="Full name" placeholder="Your full name" icon={UserRound} /><Field label="Email address" type="email" placeholder="you@example.com" icon={Mail} /><Field label="Phone number" type="tel" placeholder="+1 (555) 000-0000" icon={Phone} /><Field label="Password" type="password" placeholder="Create a password" icon={LockKeyhole} /></div>{role === 'patient' && <Field label="Date of birth" type="date" />}{role === 'doctor' && <div className="grid gap-4 sm:grid-cols-2"><Field label="Designation" placeholder="e.g. MD, MBBS" /><Field label="Specialty" placeholder="e.g. Cardiology" /><Field label="Consultation fee" placeholder="$ 0.00" /><Field label="Qualifications" placeholder="e.g. FACC, PhD" /></div>}{role !== 'staff' && <Field label="Confirm password" type="password" placeholder="Repeat your password" icon={LockKeyhole} />}<label className="flex items-start gap-2 text-xs leading-5 text-[#6a8189]"><input type="checkbox" className="mt-1 size-4 rounded border-[#c9dadd] accent-[#5367df]" required /> I agree to the <button type="button" className="font-bold text-[#5367df]">Terms of Service</button> and <button type="button" className="font-bold text-[#5367df]">Privacy Policy</button>.</label><button className="flex h-11 items-center justify-center gap-2 rounded-xl bg-[#5367df] text-sm font-bold text-white shadow-lg shadow-[#5367df]/20">Create account <ArrowRight className="size-4" /></button></form><button onClick={() => go('role')} className="mt-6 flex items-center gap-2 text-sm font-bold text-[#71878f]"><ArrowLeft className="size-4" /> Choose a different account</button></AuthShell> }

function Forgot({ go }: { go: (screen: Screen) => void }) { return <AuthShell eyebrow="Account recovery" title="Forgot your password?" copy="Enter your email and we’ll send you a secure link to reset your password."><form onSubmit={(e) => { e.preventDefault(); go('reset') }} className="flex flex-col gap-5"><Field label="Email address" type="email" placeholder="you@example.com" icon={Mail} /><button className="h-11 rounded-xl bg-[#5367df] text-sm font-bold text-white">Send reset link</button></form><button onClick={() => go('login')} className="mx-auto mt-7 flex items-center gap-2 text-sm font-bold text-[#71878f]"><ArrowLeft className="size-4" /> Back to sign in</button></AuthShell> }
function Reset({ go }: { go: (screen: Screen) => void }) { return <AuthShell eyebrow="Set a new password" title="Create a new password" copy="Choose a strong password you haven’t used before."><form onSubmit={(e) => { e.preventDefault(); go('success') }} className="flex flex-col gap-4"><Field label="New password" type="password" placeholder="Enter new password" icon={LockKeyhole} /><div className="flex gap-1.5"><span className="h-1.5 flex-1 rounded-full bg-[#5367df]" /><span className="h-1.5 flex-1 rounded-full bg-[#5367df]" /><span className="h-1.5 flex-1 rounded-full bg-[#dfe9eb]" /><span className="h-1.5 flex-1 rounded-full bg-[#dfe9eb]" /></div><p className="-mt-2 text-xs text-[#71878f]">Good password strength · 8+ characters recommended</p><Field label="Confirm new password" type="password" placeholder="Repeat your new password" icon={LockKeyhole} /><button className="mt-2 h-11 rounded-xl bg-[#5367df] text-sm font-bold text-white">Update password</button></form></AuthShell> }
function Verify({ go }: { go: (screen: Screen) => void }) { return <AuthShell eyebrow="Almost there" title="Verify your email" copy="We sent a 6-digit verification code to your email address. Enter it below to continue."><div className="flex flex-col gap-6"><div className="flex justify-between gap-2">{[1,2,3,4,5,6].map((n) => <input key={n} inputMode="numeric" maxLength={1} aria-label={`Verification digit ${n}`} className="size-12 rounded-xl border border-[#d9e6e9] bg-white text-center text-xl font-bold text-[#294652] outline-none focus:border-[#5367df] focus:ring-4 focus:ring-[#5367df]/10" />)}</div><button onClick={() => go('success')} className="h-11 rounded-xl bg-[#5367df] text-sm font-bold text-white">Verify email</button><p className="text-center text-sm text-[#71878f]">Didn’t receive a code? <button className="font-bold text-[#5367df]">Resend code</button></p></div></AuthShell> }
function Success({ go }: { go: (screen: Screen) => void }) { return <AuthShell eyebrow="You’re all set" title="Welcome to MediBook" copy="Your account is ready. Let’s make your next healthcare visit a little easier."><div className="flex flex-col items-center rounded-2xl border border-[#d8eee1] bg-[#f2fbf5] p-8 text-center"><span className="grid size-14 place-items-center rounded-full bg-[#d8f2e1] text-[#2d8956]"><Check className="size-7" /></span><p className="mt-4 text-sm leading-6 text-[#5e7a6a]">Your account has been successfully created and verified.</p></div><button onClick={() => go('login')} className="mt-6 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#5367df] text-sm font-bold text-white">Continue to sign in <ArrowRight className="size-4" /></button></AuthShell> }

export function AuthExperience() { const [screen, setScreen] = useState<Screen>('login'); const [role, setRole] = useState<Role>('patient'); const go = (next: Screen) => setScreen(next); const content = screen === 'login' ? <Login go={go} /> : screen === 'role' ? <RoleChoice go={go} setRole={setRole} /> : screen === 'signup' ? <Signup role={role} go={go} /> : screen === 'forgot' ? <Forgot go={go} /> : screen === 'reset' ? <Reset go={go} /> : screen === 'verify' ? <Verify go={go} /> : <Success go={go} />; return <main className="min-h-screen bg-[#f7fafb] lg:flex"><VisualPanel /><section className="flex min-h-screen flex-1 items-center justify-center px-5 py-10 sm:px-10"><div className="w-full max-w-md">{screen !== 'login' && screen !== 'success' && <button onClick={() => go(screen === 'signup' ? 'role' : 'login')} className="mb-8 flex items-center gap-2 text-sm font-bold text-[#71878f] hover:text-[#5367df]"><ArrowLeft className="size-4" /> Back</button>}{content}<div className="mt-10 flex items-center justify-center gap-2 text-xs text-[#91a5ab]"><LockKeyhole className="size-3.5" /> Protected by MediBook security</div></div></section></main> }
