"use client"

import { useMemo, useState, type ReactNode } from "react"
import { Check, Download, FileText, Printer, Receipt, Search, X } from "lucide-react"

const transactions = [
  { id: "TXN-2026-00981", patient: "Sarah Johnson", doctor: "Dr. Michael Anderson", appointment: "APT-2026-004821", amount: "$120.00", status: "PAID", date: "Sep 21, 2026 · 09:30 AM" },
  { id: "TXN-2026-00982", patient: "Robert Williams", doctor: "Dr. Emily Carter", appointment: "APT-2026-004822", amount: "$85.00", status: "PENDING", date: "Sep 21, 2026 · 10:00 AM" },
  { id: "TXN-2026-00983", patient: "Jessica Brown", doctor: "Dr. Michael Anderson", appointment: "APT-2026-004823", amount: "$120.00", status: "PAID", date: "Sep 21, 2026 · 10:30 AM" },
  { id: "TXN-2026-00974", patient: "David Miller", doctor: "Dr. James Wilson", appointment: "APT-2026-004810", amount: "$95.00", status: "REFUNDED", date: "Sep 20, 2026 · 11:00 AM" },
  { id: "TXN-2026-00969", patient: "Maria Garcia", doctor: "Dr. Emily Carter", appointment: "APT-2026-004805", amount: "$85.00", status: "PENDING", date: "Sep 20, 2026 · 11:30 AM" },
]

type Transaction = typeof transactions[number]

export function StaffBilling() {
  const [query, setQuery] = useState("")
  const [status, setStatus] = useState("All statuses")
  const [selected, setSelected] = useState<Transaction | null>(null)
  const [notice, setNotice] = useState("")
  const filtered = useMemo(() => transactions.filter((tx) => `${tx.id} ${tx.patient} ${tx.doctor}`.toLowerCase().includes(query.toLowerCase()) && (status === "All statuses" || tx.status === status)), [query, status])
  const action = (text: string) => { setNotice(text); setTimeout(() => setNotice(""), 2500) }

  return <div className="mt-8 flex flex-col gap-5">
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Today&apos;s revenue" value="$2,480" tone="bg-[#e9f8f3] text-[#258c70]" /><Metric label="Pending payments" value="$1,240" tone="bg-[#fff3e7] text-[#d68b42]" /><Metric label="Refunded payments" value="$285" tone="bg-[#fff0ef] text-[#c9776d]" /><Metric label="Total transactions" value="42" tone="bg-[#edf3ff] text-primary" /></div>
    <section className="rounded-2xl border border-border bg-card shadow-sm"><div className="flex flex-col gap-4 border-b border-border p-5 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="font-bold">Payment transactions</h2><p className="mt-1 text-xs text-muted-foreground">{filtered.length} transactions match your filters</p></div><div className="flex flex-wrap gap-2"><button onClick={() => action("Transaction export prepared")} className="inline-flex items-center gap-2 rounded-xl border border-border px-3 py-2 text-xs font-bold hover:bg-secondary"><Download className="size-3.5" />Export</button><button onClick={() => action("Receipt printer ready")} className="inline-flex items-center gap-2 rounded-xl bg-primary px-3 py-2 text-xs font-bold text-primary-foreground hover:opacity-90"><Printer className="size-3.5" />Print report</button></div></div>
      <div className="flex flex-wrap gap-3 border-b border-border p-4"><label className="relative min-w-[220px] flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input aria-label="Search transactions" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search patient, doctor, or transaction ID" className="h-10 w-full rounded-xl border border-border bg-background pl-9 pr-3 text-xs outline-none focus:border-primary focus:ring-2 focus:ring-primary/15" /></label><input aria-label="Start date" type="date" defaultValue="2026-09-01" className="h-10 rounded-xl border border-border bg-background px-3 text-xs" /><input aria-label="End date" type="date" defaultValue="2026-09-21" className="h-10 rounded-xl border border-border bg-background px-3 text-xs" /><select aria-label="Doctor filter" className="h-10 rounded-xl border border-border bg-background px-3 text-xs"><option>All doctors</option><option>Dr. Michael Anderson</option><option>Dr. Emily Carter</option></select><select aria-label="Payment status" value={status} onChange={(e) => setStatus(e.target.value)} className="h-10 rounded-xl border border-border bg-background px-3 text-xs"><option>All statuses</option><option>PAID</option><option>PENDING</option><option>REFUNDED</option></select></div>
      <div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="bg-secondary/60 text-[10px] font-bold uppercase tracking-wider text-muted-foreground"><tr>{["Transaction ID","Patient","Doctor","Appointment","Amount","Payment status","Date","Actions"].map((h) => <th key={h} className="whitespace-nowrap px-5 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-border">{filtered.map((tx) => <Row key={tx.id} tx={tx} onView={() => setSelected(tx)} onAction={action} />)}</tbody></table></div><div className="flex flex-col gap-3 p-4 md:hidden">{filtered.map((tx) => <div key={tx.id} className="rounded-xl border border-border p-4"><div className="flex items-start justify-between"><div><p className="font-bold">{tx.patient}</p><p className="mt-1 text-[11px] text-muted-foreground">{tx.id} · {tx.date}</p></div><Badge status={tx.status} /></div><div className="mt-4 flex items-center justify-between"><div><p className="text-xs text-muted-foreground">{tx.doctor}</p><p className="mt-1 font-black">{tx.amount}</p></div><button onClick={() => setSelected(tx)} className="rounded-lg border border-border px-3 py-1.5 text-[11px] font-bold">View details</button></div></div>)}</div>{filtered.length === 0 && <div className="p-12 text-center text-sm text-muted-foreground">No transactions match these filters.</div>}</section>
    {selected && <PaymentDrawer tx={selected} onClose={() => setSelected(null)} onAction={action} />}{notice && <div role="status" className="fixed bottom-6 right-5 z-[70] flex items-center gap-2 rounded-xl border border-border bg-card px-4 py-3 text-sm font-semibold shadow-lg"><Check className="size-4 text-primary" />{notice}</div>}
  </div>
}

function Row({ tx, onView, onAction }: { tx: Transaction; onView: () => void; onAction: (text: string) => void }) { return <tr className="hover:bg-secondary/30"><td className="px-5 py-4 text-xs font-bold text-primary">{tx.id}</td><td className="px-5 py-4 font-bold">{tx.patient}</td><td className="px-5 py-4 text-xs text-muted-foreground">{tx.doctor}</td><td className="px-5 py-4 text-xs text-muted-foreground">{tx.appointment}</td><td className="px-5 py-4 font-black">{tx.amount}</td><td className="px-5 py-4"><Badge status={tx.status} /></td><td className="whitespace-nowrap px-5 py-4 text-xs text-muted-foreground">{tx.date}</td><td className="px-5 py-4"><button onClick={onView} className="rounded-lg border border-border px-3 py-1.5 text-[11px] font-bold hover:bg-secondary">View</button></td></tr> }
function Metric({ label, value, tone }: { label: string; value: string; tone: string }) { return <div className="rounded-2xl border border-border bg-card p-4 shadow-sm"><div className={`mb-3 inline-flex rounded-lg px-2.5 py-1.5 text-lg font-black ${tone}`}>{value}</div><p className="text-xs text-muted-foreground">{label}</p></div> }
function Badge({ status }: { status: string }) { return <span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${status === "PAID" ? "bg-[#e9f8f3] text-[#258c70]" : status === "PENDING" ? "bg-[#fff3e7] text-[#b8742c]" : "bg-[#fff0ef] text-[#bd6c63]"}`}>{status}</span> }
function PaymentDrawer({ tx, onClose, onAction }: { tx: Transaction; onClose: () => void; onAction: (text: string) => void }) { return <><div className="fixed inset-0 z-50 bg-foreground/20" onClick={onClose} aria-hidden="true" /><aside role="dialog" aria-label="Payment details" className="fixed inset-y-0 right-0 z-[60] flex w-full max-w-[480px] flex-col overflow-y-auto border-l border-border bg-card shadow-2xl"><div className="flex items-center justify-between border-b border-border p-5"><div><p className="text-[10px] font-bold uppercase tracking-wider text-primary">Payment detail</p><h2 className="mt-1 text-lg font-black">{tx.id}</h2></div><button onClick={onClose} className="rounded-lg p-2 hover:bg-secondary" aria-label="Close details"><X className="size-5" /></button></div><div className="flex flex-1 flex-col gap-5 p-5"><div className="rounded-2xl bg-secondary/60 p-5"><div className="flex items-start justify-between"><div><p className="text-sm font-bold">{tx.patient}</p><p className="mt-1 text-xs text-muted-foreground">{tx.doctor}</p></div><Badge status={tx.status} /></div><p className="mt-5 text-3xl font-black">{tx.amount}</p><p className="mt-1 text-xs text-muted-foreground">{tx.date}</p></div><div className="grid gap-3 sm:grid-cols-2"><Info label="Appointment" value={tx.appointment} /><Info label="Payment method" value="Visa •••• 4242" /><Info label="Service" value="General consultation" /><Info label="Receipt number" value="RCP-2026-00981" /></div><div className="rounded-2xl border border-border p-5"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><Receipt className="size-5" /></div><div><p className="font-bold">Professional receipt</p><p className="text-xs text-muted-foreground">MediBook Healthcare · Tax invoice</p></div></div><div className="mt-5 flex items-center justify-between border-t border-border pt-4 text-sm"><span className="text-muted-foreground">Consultation fee</span><strong>{tx.amount}</strong></div><div className="mt-2 flex items-center justify-between text-sm"><span className="text-muted-foreground">Total paid</span><strong className="text-primary">{tx.amount}</strong></div></div><div className="mt-auto flex flex-wrap gap-2"><button onClick={() => onAction(tx.status === "PENDING" ? "Payment marked as paid" : "Payment already settled")} className="flex-1 rounded-xl bg-primary px-4 py-3 text-xs font-bold text-primary-foreground">Mark paid</button><button onClick={() => onAction("Refund request created")} className="flex-1 rounded-xl border border-border px-4 py-3 text-xs font-bold hover:bg-secondary">Issue refund</button><button onClick={() => onAction("Receipt ready to print")} className="inline-flex items-center gap-2 rounded-xl border border-border px-4 py-3 text-xs font-bold hover:bg-secondary"><Printer className="size-4" />Print receipt</button></div></div></aside></> }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-border p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 text-xs font-bold">{value}</p></div> }
function PlaceholderIcon() { return <FileText className="size-4" /> }
void PlaceholderIcon
