"use client"

import { useState } from "react"
import { AlertCircle, ArrowLeft, CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, Download, FileText, ShieldCheck } from "lucide-react"

const steps = ["Doctor", "Date & Time", "Symptoms", "Confirmation", "Success"]
const dates = ["Tue, Sep 22", "Wed, Sep 23", "Thu, Sep 24", "Fri, Sep 25", "Sat, Sep 26"]
const times = ["09:00 AM", "09:20 AM", "10:00 AM", "10:30 AM", "02:00 PM", "02:40 PM", "04:20 PM", "05:00 PM"]
const tags = ["Chest pain", "Headache", "Fever", "Follow-up", "Routine consultation"]

export function BookingFlow({ onBack, onDashboard }: { onBack: () => void; onDashboard: () => void }) {
  const [step, setStep] = useState(0)
  const [date, setDate] = useState(dates[2])
  const [time, setTime] = useState("10:30 AM")
  const [symptoms, setSymptoms] = useState("")
  const [selectedTags, setSelectedTags] = useState<string[]>(["Routine consultation"])
  const [status, setStatus] = useState<"idle" | "loading" | "conflict" | "failure">("idle")
  const [confirmed, setConfirmed] = useState(false)

  const toggleTag = (tag: string) => setSelectedTags((current) => current.includes(tag) ? current.filter((item) => item !== tag) : [...current, tag])
  const continueBooking = () => setStep((current) => Math.min(current + 1, 3))
  const confirm = () => {
    setStatus("loading")
    window.setTimeout(() => { setStatus("idle"); setConfirmed(true); setStep(4) }, 850)
  }
  const retry = () => { setStatus("idle"); setStep(3) }

  if (confirmed) return <SuccessState onDashboard={onDashboard} onBack={() => { setConfirmed(false); setStep(3) }} />

  return <div className="mx-auto max-w-5xl">
    <button onClick={onBack} className="mb-6 flex items-center gap-2 text-sm font-bold text-muted-foreground hover:text-primary"><ArrowLeft className="size-4" /> Back to doctor</button>
    <div className="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-8">
      <div className="mb-8 overflow-x-auto pb-2"><div className="flex min-w-[620px] items-start justify-between">{steps.map((label, index) => <div key={label} className="flex flex-1 items-start last:flex-none"><div className="flex flex-col items-center gap-2"><div className={`grid size-9 place-items-center rounded-full border-2 text-xs font-black ${index < step ? "border-primary bg-primary text-primary-foreground" : index === step ? "border-primary bg-primary/10 text-primary" : "border-border bg-background text-muted-foreground"}`}>{index < step ? <Check className="size-4" /> : index + 1}</div><span className={`whitespace-nowrap text-[11px] font-bold ${index === step ? "text-primary" : "text-muted-foreground"}`}>{label}</span></div>{index < steps.length - 1 && <div className={`mt-4 h-px flex-1 ${index < step ? "bg-primary" : "bg-border"}`} />}</div>)}</div></div>
      {step === 0 && <DoctorStep onContinue={continueBooking} />}
      {step === 1 && <DateTimeStep date={date} time={time} setDate={setDate} setTime={setTime} onBack={() => setStep(0)} onContinue={continueBooking} />}
      {step === 2 && <SymptomsStep symptoms={symptoms} setSymptoms={setSymptoms} selectedTags={selectedTags} toggleTag={toggleTag} onBack={() => setStep(1)} onContinue={continueBooking} />}
      {step === 3 && <ConfirmationStep date={date} time={time} symptoms={symptoms} tags={selectedTags} status={status} onBack={() => setStep(2)} onConfirm={confirm} onRetry={retry} />}
    </div>
  </div>
}

function DoctorStep({ onContinue }: { onContinue: () => void }) { return <div><Heading eyebrow="Step 1 of 5" title="Confirm your doctor" description="You are booking a visit with the selected provider." /><div className="mt-7 flex flex-col gap-4 rounded-2xl border border-primary/20 bg-primary/5 p-5 sm:flex-row sm:items-center"><div className="grid size-16 shrink-0 place-items-center rounded-2xl bg-[#dce8ff] text-lg font-black text-primary">MA</div><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-black">Dr. Michael Anderson</h2><span className="rounded-full bg-[#e9f8f3] px-2 py-1 text-[10px] font-black text-[#218765]">Verified</span></div><p className="mt-1 text-sm font-semibold text-primary">Senior Consultant Cardiologist</p><p className="mt-1 text-xs text-muted-foreground">Heart & Vascular Center · New York, NY</p></div><div className="text-left sm:text-right"><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Consultation fee</p><p className="text-xl font-black">$85</p></div></div><ActionRow label="Continue to date & time" onClick={onContinue} /> </div> }

function DateTimeStep({ date, time, setDate, setTime, onBack, onContinue }: { date: string; time: string; setDate: (v: string) => void; setTime: (v: string) => void; onBack: () => void; onContinue: () => void }) { return <div><Heading eyebrow="Step 2 of 5" title="Choose your date & time" description="Available slots are reserved atomically when you confirm." /><div className="mt-7 grid gap-8 lg:grid-cols-[1fr_1.15fr]"><div><label className="text-xs font-black uppercase tracking-wider text-muted-foreground">Select a date</label><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{dates.map((item) => <button key={item} onClick={() => setDate(item)} className={`rounded-xl border px-3 py-4 text-left text-xs font-black ${date === item ? "border-primary bg-primary text-primary-foreground" : "border-border hover:border-primary"}`}><CalendarDays className="mb-2 size-4" />{item}</button>)}</div></div><div><label className="text-xs font-black uppercase tracking-wider text-muted-foreground">Available times</label><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{times.map((item, index) => <button key={item} onClick={() => setTime(item)} disabled={index === 5} className={`rounded-xl border px-3 py-3 text-xs font-black ${time === item ? "border-primary bg-primary text-primary-foreground" : index === 5 ? "cursor-not-allowed bg-muted text-muted-foreground line-through" : "border-border hover:border-primary"}`}>{item}</button>)}</div><p className="mt-3 flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="size-4 text-[#218765]" /> Your selected slot is held during confirmation.</p></div></div><ActionRow label="Continue to symptoms" onClick={onContinue} onBack={onBack} /></div> }

function SymptomsStep({ symptoms, setSymptoms, selectedTags, toggleTag, onBack, onContinue }: { symptoms: string; setSymptoms: (v: string) => void; selectedTags: string[]; toggleTag: (v: string) => void; onBack: () => void; onContinue: () => void }) { return <div><Heading eyebrow="Step 3 of 5" title="What brings you in?" description="Share a few details so your doctor can prepare for your visit." /><div className="mt-7"><label htmlFor="symptoms" className="text-sm font-black">Tell us about your symptoms <span className="font-medium text-muted-foreground">(optional)</span></label><textarea id="symptoms" value={symptoms} onChange={(event) => setSymptoms(event.target.value)} placeholder="Describe what you have been experiencing..." className="mt-3 min-h-40 w-full resize-y rounded-xl border border-border bg-background p-4 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/15" /><p className="mt-2 text-right text-xs text-muted-foreground">{symptoms.length}/500</p><p className="mt-5 text-sm font-black">Or choose common reasons</p><div className="mt-3 flex flex-wrap gap-2">{tags.map((tag) => <button key={tag} onClick={() => toggleTag(tag)} className={`rounded-full border px-3 py-2 text-xs font-bold ${selectedTags.includes(tag) ? "border-primary bg-primary/10 text-primary" : "border-border text-muted-foreground hover:border-primary"}`}>{tag}</button>)}</div></div><ActionRow label="Review appointment" onClick={onContinue} onBack={onBack} /></div> }

function ConfirmationStep({ date, time, symptoms, tags, status, onBack, onConfirm, onRetry }: { date: string; time: string; symptoms: string; tags: string[]; status: string; onBack: () => void; onConfirm: () => void; onRetry: () => void }) { return <div><Heading eyebrow="Step 4 of 5" title="Review and confirm" description="Please check the details before reserving this appointment." /><div className="mt-7 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-2xl border border-border bg-background p-5"><SummaryRow label="Doctor" value="Dr. Michael Anderson · Cardiology" /><SummaryRow label="Date & time" value={`${date} · ${time}`} /><SummaryRow label="Clinic" value="Heart & Vascular Center, New York" /><SummaryRow label="Patient" value="Sarah Johnson · sarah.johnson@example.com" /><SummaryRow label="Symptoms" value={symptoms || tags.join(", ") || "Routine consultation"} /></div><div className="rounded-2xl border border-border bg-secondary/50 p-5"><p className="text-xs font-black uppercase tracking-wider text-muted-foreground">Payment status</p><div className="mt-3 flex items-center justify-between"><span className="text-lg font-black">Consultation fee</span><span className="text-2xl font-black">$85</span></div><div className="mt-4 flex items-center gap-2 rounded-xl border border-[#f1d8a9] bg-[#fff9ed] px-3 py-3 text-xs font-bold text-[#a66d1c]"><Clock3 className="size-4" /> Pending</div><p className="mt-4 text-xs leading-5 text-muted-foreground">No payment is captured until your appointment is successfully reserved.</p></div></div>{status === "loading" && <div role="status" className="mt-5 flex items-center gap-3 rounded-xl border border-primary/20 bg-primary/5 p-4 text-sm font-bold text-primary"><span className="size-4 animate-spin rounded-full border-2 border-primary/30 border-t-primary" /> Reserving your slot securely. Please don&apos;t close this window.</div>}{status === "conflict" && <ErrorBox title="This slot was just booked" text="Choose another available time to continue." onClick={onRetry} />}{status === "failure" && <ErrorBox title="Booking could not be completed" text="We couldn&apos;t reserve this appointment. Please try again." onClick={onRetry} />}<ActionRow label={status === "loading" ? "Reserving..." : "Confirm Appointment"} onClick={onConfirm} onBack={onBack} disabled={status === "loading"} /></div> }

function SuccessState({ onDashboard, onBack }: { onDashboard: () => void; onBack: () => void }) { return <div className="mx-auto min-w-0 max-w-2xl overflow-hidden rounded-2xl border border-border bg-card p-6 text-center shadow-sm sm:p-10"><div className="mx-auto grid size-16 place-items-center rounded-full bg-[#e9f8f3] text-[#218765]"><Check className="size-8" /></div><p className="mt-5 text-xs font-black uppercase tracking-wider text-primary">Step 5 of 5 · Success</p><h1 className="mt-2 text-3xl font-black tracking-tight">Appointment confirmed!</h1><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-muted-foreground">Your appointment is reserved and ready. We&apos;ll send a confirmation to your email.</p><div className="mt-7 rounded-2xl bg-secondary p-5 text-left"><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Appointment ID</p><p className="mt-1 text-xl font-black tracking-wide">APT-2026-004821</p><div className="mt-5 grid gap-4 sm:grid-cols-3"><SummaryRow label="Doctor" value="Dr. Michael Anderson" /><SummaryRow label="Date" value="Thu, Sep 24" /><SummaryRow label="Time" value="10:30 AM" /><SummaryRow label="Clinic" value="Heart & Vascular Center" /></div></div><div className="mt-7 grid gap-2 sm:grid-cols-2"><button onClick={() => undefined} className="rounded-xl border border-border px-4 py-3 text-sm font-black hover:bg-secondary"><FileText className="mr-2 inline size-4" /> View Appointment</button><button onClick={() => undefined} className="rounded-xl border border-border px-4 py-3 text-sm font-black hover:bg-secondary"><CalendarDays className="mr-2 inline size-4" /> Add to Calendar</button><button onClick={() => undefined} className="rounded-xl border border-border px-4 py-3 text-sm font-black hover:bg-secondary"><Download className="mr-2 inline size-4" /> Download Confirmation</button><button onClick={onDashboard} className="rounded-xl bg-primary px-4 py-3 text-sm font-black text-primary-foreground hover:opacity-90">Back to Dashboard</button></div><button onClick={onBack} className="mt-5 text-sm font-bold text-muted-foreground hover:text-primary">Book another appointment</button></div> }

function Heading({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div><p className="text-xs font-black uppercase tracking-wider text-primary">{eyebrow}</p><h1 className="mt-2 text-2xl font-black tracking-tight sm:text-3xl">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{description}</p></div> }
function ActionRow({ label, onClick, onBack, disabled }: { label: string; onClick: () => void; onBack?: () => void; disabled?: boolean }) { return <div className="mt-8 flex flex-col-reverse gap-3 border-t border-border pt-5 sm:flex-row sm:justify-end">{onBack && <button onClick={onBack} disabled={disabled} className="rounded-xl border border-border px-5 py-3 text-sm font-black hover:bg-secondary disabled:opacity-50">Back</button>}<button onClick={onClick} disabled={disabled} className="rounded-xl bg-primary px-5 py-3 text-sm font-black text-primary-foreground shadow-sm hover:opacity-90 disabled:cursor-wait disabled:opacity-60">{label}<ChevronRight className="ml-2 inline size-4" /></button></div> }
function SummaryRow({ label, value }: { label: string; value: string }) { return <div className="border-b border-border py-3 last:border-0"><p className="text-[10px] font-black uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 text-sm font-bold">{value}</p></div> }
function ErrorBox({ title, text, onClick }: { title: string; text: string; onClick: () => void }) { return <div role="alert" className="mt-5 flex items-start gap-3 rounded-xl border border-[#f0d2cc] bg-[#fff8f6] p-4 text-[#b86f63]"><AlertCircle className="mt-0.5 size-5 shrink-0" /><div className="flex-1"><p className="text-sm font-black">{title}</p><p className="mt-1 text-xs">{text}</p></div><button onClick={onClick} className="text-xs font-black underline">Try again</button></div> }
