"use client"

import { useMemo, useState } from "react"
import { AlertCircle, Bell, CalendarClock, Check, ChevronRight, CreditCard, FileText, Mail, Settings2, ShieldCheck, Stethoscope, Trash2, X } from "lucide-react"

type Category = "Appointment" | "Payment" | "Prescription" | "Schedule" | "System"
type Notification = { id: number; category: Category; title: string; description: string; time: string; unread: boolean; related?: string }

const initialNotifications: Notification[] = [
  { id: 1, category: "Appointment", title: "Appointment booked", description: "Sarah Johnson booked a cardiology follow-up for Sep 24 at 10:30 AM.", time: "8 min ago", unread: true, related: "APT-2026-004821" },
  { id: 2, category: "Appointment", title: "Appointment reminder", description: "Your appointment with Dr. Michael Chen starts tomorrow at 10:30 AM.", time: "1 hour ago", unread: true, related: "APT-2026-004821" },
  { id: 3, category: "Payment", title: "Payment received", description: "Payment of $120.00 was received for appointment APT-2026-004821.", time: "3 hours ago", unread: true },
  { id: 4, category: "Prescription", title: "Prescription issued", description: "Dr. Michael Anderson issued a new prescription for Sarah Johnson.", time: "Yesterday", unread: false },
  { id: 5, category: "Schedule", title: "Doctor schedule changed", description: "Dr. Emily Carter opened new appointment slots for Friday, Sep 25.", time: "Yesterday", unread: false },
  { id: 6, category: "Appointment", title: "Appointment rescheduled", description: "Robert Williams moved his appointment from Sep 22 to Sep 23 at 2:00 PM.", time: "Sep 19", unread: false, related: "APT-2026-004790" },
  { id: 7, category: "Appointment", title: "Appointment cancelled", description: "Appointment APT-2026-004744 was cancelled and the patient was notified.", time: "Sep 18", unread: false, related: "APT-2026-004744" },
  { id: 8, category: "System", title: "System notification", description: "MediBook security settings were updated successfully.", time: "Sep 17", unread: false },
]

const preferences = [
  ["Appointment updates", "Bookings, reschedules, cancellations, and reminders"],
  ["Payment updates", "Payment received, pending, and refund notifications"],
  ["Prescription updates", "New prescriptions and medication changes"],
  ["Schedule changes", "Doctor availability and clinic schedule updates"],
  ["System notifications", "Security, account, and platform announcements"],
] as const

export function NotificationCenter({ role = "patient" }: { role?: "patient" | "doctor" | "staff" | "admin" }) {
  const [notifications, setNotifications] = useState(initialNotifications)
  const [filter, setFilter] = useState<"All" | Category>("All")
  const [tab, setTab] = useState<"Notifications" | "Preferences">("Notifications")
  const [channels, setChannels] = useState<Record<string, boolean>>({ email: true, push: true, sms: false })
  const [saved, setSaved] = useState(false)
  const visible = useMemo(() => filter === "All" ? notifications : notifications.filter((item) => item.category === filter), [filter, notifications])
  const unread = notifications.filter((item) => item.unread).length
  const markRead = (id: number) => setNotifications((items) => items.map((item) => item.id === id ? { ...item, unread: false } : item))
  const markAll = () => setNotifications((items) => items.map((item) => ({ ...item, unread: false })))
  const remove = (id: number) => setNotifications((items) => items.filter((item) => item.id !== id))

  return <section className="mt-8 max-w-5xl space-y-5">
    <div className="flex flex-col gap-4 rounded-2xl border border-border bg-card p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between sm:p-6"><div><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-[#edf3ff] text-primary"><Bell className="size-5" /></div><div><h2 className="font-bold">Notification center</h2><p className="mt-1 text-xs text-muted-foreground">Stay on top of activity across your {role} account.</p></div></div></div><div className="flex items-center gap-2"><span className="rounded-full bg-[#fff3e7] px-3 py-1.5 text-xs font-bold text-[#c98237]">{unread} unread</span><button onClick={markAll} className="rounded-xl border border-border px-3 py-2 text-xs font-bold hover:bg-secondary">Mark all as read</button></div></div>
    <div className="flex gap-1 rounded-xl border border-border bg-card p-1"><button onClick={() => setTab("Notifications")} className={`flex-1 rounded-lg px-3 py-2 text-sm font-bold ${tab === "Notifications" ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-secondary"}`}>Notifications</button><button onClick={() => setTab("Preferences")} className={`flex-1 rounded-lg px-3 py-2 text-sm font-bold ${tab === "Preferences" ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-secondary"}`}>Notification preferences</button></div>
    {tab === "Notifications" ? <><div className="flex gap-2 overflow-x-auto pb-1">{(["All", "Appointment", "Payment", "Prescription", "Schedule", "System"] as const).map((item) => <button key={item} onClick={() => setFilter(item)} className={`whitespace-nowrap rounded-full border px-3 py-1.5 text-xs font-bold ${filter === item ? "border-primary bg-primary text-primary-foreground" : "border-border text-muted-foreground hover:bg-secondary"}`}>{item}</button>)}</div><div className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><div className="divide-y divide-border">{visible.length ? visible.map((item) => <NotificationRow key={item.id} item={item} onRead={() => markRead(item.id)} onDelete={() => remove(item.id)} />) : <div className="p-12 text-center"><Bell className="mx-auto size-8 text-muted-foreground/50" /><p className="mt-3 font-bold">No notifications here</p><p className="mt-1 text-sm text-muted-foreground">You&apos;re all caught up.</p></div>}</div></div></> : <Preferences channels={channels} setChannels={setChannels} saved={saved} onSave={() => { setSaved(true); setTimeout(() => setSaved(false), 2200) }} />}
  </section>
}

function NotificationRow({ item, onRead, onDelete }: { item: Notification; onRead: () => void; onDelete: () => void }) { const Icon = item.category === "Appointment" ? CalendarClock : item.category === "Payment" ? CreditCard : item.category === "Prescription" ? FileText : item.category === "Schedule" ? Stethoscope : ShieldCheck; return <article className={`group flex gap-3 p-4 transition sm:gap-4 sm:p-5 ${item.unread ? "bg-[#f7faff]" : "bg-card"}`}><div className={`mt-0.5 grid size-10 shrink-0 place-items-center rounded-xl ${item.unread ? "bg-primary text-primary-foreground" : "bg-secondary text-primary"}`}><Icon className="size-4" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-bold">{item.title}</h3><span className="rounded-full bg-secondary px-2 py-0.5 text-[10px] font-bold text-muted-foreground">{item.category}</span>{item.unread && <span className="size-2 rounded-full bg-primary" aria-label="Unread" />}</div><p className="mt-1 text-sm leading-6 text-muted-foreground">{item.description}</p><div className="mt-2 flex flex-wrap items-center gap-3 text-[11px] font-semibold text-muted-foreground"><span>{item.time}</span>{item.related && <button onClick={onRead} className="inline-flex items-center gap-1 text-primary hover:underline">View related appointment <ChevronRight className="size-3" /></button>}</div></div><div className="flex shrink-0 items-start gap-1 opacity-100 sm:opacity-0 sm:transition sm:group-hover:opacity-100"><button onClick={onRead} aria-label={item.unread ? "Mark as read" : "Mark as unread"} title={item.unread ? "Mark as read" : "Mark as unread"} className="rounded-lg p-2 text-muted-foreground hover:bg-secondary hover:text-primary"><Check className="size-4" /></button><button onClick={onDelete} aria-label="Delete notification" title="Delete notification" className="rounded-lg p-2 text-muted-foreground hover:bg-[#fff0ef] hover:text-[#c9776d]"><Trash2 className="size-4" /></button></div></article> }

function Preferences({ channels, setChannels, saved, onSave }: { channels: Record<string, boolean>; setChannels: (value: Record<string, boolean>) => void; saved: boolean; onSave: () => void }) { return <div className="grid gap-5 lg:grid-cols-[1.4fr_1fr]"><div className="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-6"><div className="flex items-start justify-between"><div><h2 className="font-bold">Notification types</h2><p className="mt-1 text-xs text-muted-foreground">Choose which updates you want to receive.</p></div><Settings2 className="size-5 text-primary" /></div><div className="mt-5 divide-y divide-border">{preferences.map(([title, detail]) => <label key={title} className="flex items-center justify-between gap-4 py-4"><span><span className="block text-sm font-bold">{title}</span><span className="mt-1 block text-xs text-muted-foreground">{detail}</span></span><input type="checkbox" defaultChecked className="size-4 accent-primary" /></label>)}</div></div><div className="h-fit rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-6"><div className="flex items-start justify-between"><div><h2 className="font-bold">Delivery channels</h2><p className="mt-1 text-xs text-muted-foreground">Control where alerts arrive.</p></div><Mail className="size-5 text-primary" /></div><div className="mt-5 space-y-3">{([["email", "Email notifications"], ["push", "Push notifications"], ["sms", "SMS notifications"]] as const).map(([key, label]) => <label key={key} className="flex items-center justify-between rounded-xl border border-border p-3 text-sm font-semibold"><span>{label}</span><input type="checkbox" checked={channels[key]} onChange={(event) => setChannels({ ...channels, [key]: event.target.checked })} className="size-4 accent-primary" /></label>)}</div><button onClick={onSave} className="mt-5 w-full rounded-xl bg-primary py-2.5 text-xs font-bold text-primary-foreground hover:opacity-90">{saved ? "Preferences saved" : "Save preferences"}</button></div></div> }
