"use client"

import { useState } from "react"
import {
  Activity, ArrowUpRight, CalendarDays, Check, Clock3, Download, FileText, HeartPulse,
  MapPin, MoreHorizontal, Pill, Plus, RefreshCw, Stethoscope, Video,
} from "lucide-react"
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"

const specialtyData = [
  { name: "Cardiology", value: 42, color: "#4f6ef7" },
  { name: "Dermatology", value: 25, color: "#67c7b6" },
  { name: "Internal Medicine", value: 20, color: "#f4b36a" },
  { name: "Pediatrics", value: 13, color: "#b596ef" },
]
const expenseData = [
  { month: "Apr", amount: 280 }, { month: "May", amount: 420 }, { month: "Jun", amount: 360 },
  { month: "Jul", amount: 580 }, { month: "Aug", amount: 440 }, { month: "Sep", amount: 690 },
]
const timeline = [
  { date: "Sep 24", title: "Cardiology follow-up", doctor: "Dr. Michael Anderson", status: "Upcoming", icon: CalendarDays },
  { date: "Sep 12", title: "Annual skin screening", doctor: "Dr. Olivia Bennett", status: "Completed", icon: Check },
  { date: "Aug 28", title: "Primary care visit", doctor: "Dr. James Wilson", status: "Completed", icon: Stethoscope },
]
const prescriptions = [
  { name: "Atorvastatin 20mg", doctor: "Dr. Michael Anderson", date: "Sep 12, 2026", status: "Active" },
  { name: "Lisinopril 10mg", doctor: "Dr. James Wilson", date: "Aug 28, 2026", status: "Active" },
  { name: "Vitamin D3 1000 IU", doctor: "Dr. Olivia Bennett", date: "Aug 14, 2026", status: "Refill due" },
]

export function PatientDashboard() {
  const [loading, setLoading] = useState(false)
  const [notice, setNotice] = useState("")
  const reload = () => { setLoading(true); setNotice(""); window.setTimeout(() => setLoading(false), 650) }
  const action = (label: string) => setNotice(`${label} is ready to open.`)

  if (loading) return <div className="grid gap-5 lg:grid-cols-2">{[1, 2, 3, 4].map((item) => <div key={item} className="h-44 animate-pulse rounded-2xl border border-border bg-card" />)}</div>

  return <div className="flex flex-col gap-5">
    {notice && <div role="status" className="flex items-center justify-between rounded-xl border border-primary/20 bg-primary/5 px-4 py-3 text-sm font-semibold text-primary"><span>{notice}</span><button onClick={() => setNotice("")} aria-label="Dismiss notification"><Check className="size-4" /></button></div>}
    <section className="grid gap-5 xl:grid-cols-[1.35fr_1fr]">
      <div className="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-primary">Next appointment</p><h2 className="mt-2 text-xl font-black">Dr. Michael Anderson</h2><p className="mt-1 text-sm text-muted-foreground">Cardiology · Heart & Vascular Center</p></div><div className="grid size-12 place-items-center rounded-full bg-[#dce8ff] text-sm font-black text-primary">MA</div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Detail icon={CalendarDays} label="Date" value="Thursday, Sep 24" /><Detail icon={Clock3} label="Time" value="10:30 AM" /><Detail icon={Video} label="Visit type" value="Video visit" /></div><div className="mt-5 flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#e6f7ef] px-3 py-1 text-xs font-bold text-[#278e70]">Confirmed</span><span className="text-xs text-muted-foreground">Starts in 3 days</span></div><div className="mt-5 flex flex-wrap gap-2"><button onClick={() => action("Appointment details")} className="rounded-xl bg-primary px-4 py-2.5 text-xs font-bold text-primary-foreground hover:opacity-90">View appointment</button><button onClick={() => action("Reschedule")} className="rounded-xl border border-border px-4 py-2.5 text-xs font-bold hover:bg-secondary">Reschedule</button><button onClick={() => action("Cancellation")} className="rounded-xl px-4 py-2.5 text-xs font-bold text-muted-foreground hover:bg-secondary">Cancel</button></div></div>
      <div className="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-bold">What to do next</h2><p className="mt-1 text-xs text-muted-foreground">A few helpful reminders.</p></div><HeartPulse className="size-5 text-[#67c7b6]" /></div><div className="mt-5 flex flex-col gap-3"><Reminder icon={CalendarDays} title="Prepare for your video visit" detail="Check your camera and connection." /><Reminder icon={Pill} title="Refill Lisinopril" detail="Your refill is due in 8 days." /><Reminder icon={FileText} title="Review recent results" detail="Two new documents are available." /></div></div>
    </section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Upcoming appointments" value="2" icon={CalendarDays} tone="bg-[#edf3ff] text-primary" /><Metric label="Completed visits" value="12" icon={Check} tone="bg-[#e9f8f3] text-[#2b9d7e]" /><Metric label="Active prescriptions" value="4" icon={Pill} tone="bg-[#fff3e7] text-[#d68b42]" /><Metric label="Medical expenses" value="$2,840" icon={Activity} tone="bg-[#f2ecff] text-[#8e68dc]" /></section>
    <section className="grid gap-5 xl:grid-cols-[1.15fr_1fr]"><Panel title="Appointment timeline" action="View all" onAction={() => action("All appointments")}><div className="flex flex-col gap-4">{timeline.map((item) => <div key={item.date} className="flex gap-4"><div className="flex w-14 shrink-0 flex-col items-center"><span className="text-xs font-black text-foreground">{item.date}</span><span className="mt-2 h-full w-px bg-border" /></div><div className="relative -mt-1 flex-1 rounded-xl border border-border p-3 transition hover:border-primary/30 hover:bg-primary/[0.02]"><span className={`absolute right-3 top-3 rounded-full px-2 py-1 text-[10px] font-bold ${item.status === "Upcoming" ? "bg-primary/10 text-primary" : "bg-secondary text-muted-foreground"}`}>{item.status}</span><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-lg bg-secondary text-primary"><item.icon className="size-4" /></div><div><p className="text-sm font-bold">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{item.doctor}</p></div></div></div></div>)}</div></Panel><Panel title="Appointments by specialty" action="This year"><div className="flex items-center gap-5"><div className="relative h-44 w-44 shrink-0"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={specialtyData} dataKey="value" nameKey="name" innerRadius={52} outerRadius={74} paddingAngle={3}>{specialtyData.map((entry) => <Cell key={entry.name} fill={entry.color} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 grid place-items-center"><div className="text-center"><p className="text-2xl font-black">24</p><p className="text-[10px] text-muted-foreground">visits</p></div></div></div><div className="flex flex-col gap-3">{specialtyData.map((item) => <div key={item.name} className="flex items-center gap-2 text-xs"><span className="size-2.5 rounded-full" style={{ background: item.color }} /><span className="text-muted-foreground">{item.name}</span><span className="ml-auto font-black">{item.value}%</span></div>)}</div></div></Panel></section>
    <section className="grid gap-5 xl:grid-cols-[1fr_1.15fr]"><Panel title="Recent prescriptions" action="View all" onAction={() => action("All prescriptions")}><div className="flex flex-col gap-2">{prescriptions.map((item) => <div key={item.name} className="flex items-center gap-3 rounded-xl p-2 transition hover:bg-secondary"><div className="grid size-9 place-items-center rounded-lg bg-[#fff3e7] text-[#d68b42]"><Pill className="size-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{item.name}</p><p className="truncate text-xs text-muted-foreground">{item.doctor} · {item.date}</p></div><span className={`hidden rounded-full px-2 py-1 text-[10px] font-bold sm:block ${item.status === "Active" ? "bg-[#e6f7ef] text-[#278e70]" : "bg-[#fff3e7] text-[#b97932]"}`}>{item.status}</span><button onClick={() => action(`Download for ${item.name}`)} className="rounded-lg p-2 text-muted-foreground hover:bg-card hover:text-primary" aria-label={`Download ${item.name}`}><Download className="size-4" /></button></div>)}</div></Panel><Panel title="Monthly medical expenses" action="2026"><div className="h-56"><ResponsiveContainer width="100%" height="100%"><BarChart data={expenseData} margin={{ top: 10, right: 4, left: -18, bottom: 0 }}><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: "#8ca1aa" }} /><YAxis axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: "#8ca1aa" }} tickFormatter={(value) => `$${value}`} /><Tooltip cursor={{ fill: "#f4f7fa" }} formatter={(value) => [`$${value}`, "Expenses"]} /><Bar dataKey="amount" fill="#4f6ef7" radius={[6, 6, 0, 0]} barSize={28} /></BarChart></ResponsiveContainer></div></Panel></section>
    <section className="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-bold">Quick actions</h2><p className="mt-1 text-xs text-muted-foreground">Get where you need to go faster.</p></div><MoreHorizontal className="size-5 text-muted-foreground" /></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Action icon={Stethoscope} label="Find a doctor" onClick={() => action("Find a doctor")} /><Action icon={Plus} label="Book appointment" onClick={() => action("Book appointment")} /><Action icon={Pill} label="View prescriptions" onClick={() => action("Prescriptions")} /><Action icon={FileText} label="Medical records" onClick={() => action("Medical records")} /></div></section><div className="flex justify-end"><button onClick={reload} className="flex items-center gap-2 text-xs font-bold text-muted-foreground hover:text-primary"><RefreshCw className="size-3.5" /> Refresh overview</button></div>
  </div>
}

function Panel({ title, action, onAction, children }: { title: string; action?: string; onAction?: () => void; children: React.ReactNode }) { return <div className="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-6"><div className="mb-5 flex items-center justify-between"><h2 className="font-bold">{title}</h2>{action && <button onClick={onAction} className="text-xs font-bold text-primary hover:underline">{action}</button>}</div>{children}</div> }
function Detail({ icon: Icon, label, value }: { icon: typeof CalendarDays; label: string; value: string }) { return <div className="flex items-center gap-2 rounded-xl bg-secondary p-3"><Icon className="size-4 text-primary" /><div><p className="text-[10px] font-bold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-xs font-bold">{value}</p></div></div> }
function Reminder({ icon: Icon, title, detail }: { icon: typeof CalendarDays; title: string; detail: string }) { return <div className="flex items-center gap-3 rounded-xl border border-border p-3"><div className="grid size-9 place-items-center rounded-lg bg-secondary text-primary"><Icon className="size-4" /></div><div><p className="text-xs font-bold">{title}</p><p className="mt-1 text-[11px] text-muted-foreground">{detail}</p></div></div> }
function Metric({ label, value, icon: Icon, tone }: { label: string; value: string; icon: typeof CalendarDays; tone: string }) { return <div className="flex items-center gap-3 rounded-2xl border border-border bg-card p-4 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className={`grid size-10 place-items-center rounded-xl ${tone}`}><Icon className="size-5" /></div><div><p className="text-xl font-black">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div></div> }
function Action({ icon: Icon, label, onClick }: { icon: typeof CalendarDays; label: string; onClick: () => void }) { return <button onClick={onClick} className="flex items-center gap-3 rounded-xl border border-border p-3 text-left transition hover:-translate-y-0.5 hover:border-primary/30 hover:bg-primary/[0.03]"><div className="grid size-9 place-items-center rounded-lg bg-secondary text-primary"><Icon className="size-4" /></div><span className="text-xs font-bold">{label}</span><ArrowUpRight className="ml-auto size-4 text-muted-foreground" /></button> }

export function EmptyDashboardState() { return <div className="rounded-2xl border border-dashed border-border bg-card p-10 text-center"><CalendarDays className="mx-auto size-8 text-muted-foreground" /><h2 className="mt-3 font-bold">No upcoming appointments</h2><p className="mt-1 text-sm text-muted-foreground">Book a visit with a trusted doctor to get started.</p></div> }
export function DashboardErrorState() { return <div role="alert" className="rounded-2xl border border-destructive/20 bg-destructive/5 p-6 text-sm font-semibold text-destructive">We couldn&apos;t load your health overview. Please try again.</div> }
